pipeline {
    agent any

    environment {
        SONAR_PROJECT_KEY = 'frontend'
        SONAR_PROJECT_NAME = 'Frontend'
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Install Dependencies') {
            steps {
                dir('frontend') {
                    sh 'npm install'
                }
            }
        }

        stage('Build') {
            steps {
                dir('frontend') {
                    sh 'npm run build'
                }
            }
        }

        stage('Test') {
            steps {
                dir('frontend') {
                    sh 'npm run test -- --watch=false || true'
                }
            }
        }

        stage('SonarQube Analysis') {
            steps {
                withSonarQubeEnv('sonar') {
                    dir('frontend') {
                        sh """
                        sonar-scanner \\
                        -Dsonar.projectKey=${SONAR_PROJECT_KEY} \\
                        -Dsonar.projectName='${SONAR_PROJECT_NAME}' \\
                        -Dsonar.sources=src \\
                        -Dsonar.host.url=http://localhost:9000 || echo "Sonar Scanner not installed or failed, continuing..."
                        """
                    }
                }
            }
        }
    }

    post {
        success {
            build job: 'frontend-cd', wait: false
        }
    }
}
