sonar.projectKey=learnivo-frontend
sonar.projectName=Learnivo Frontend
sonar.sourceEncoding=UTF-8

sonar.sources=src
sonar.tests=src
sonar.test.inclusions=src/**/*.spec.ts
sonar.exclusions=src/**/*.spec.ts,src/main.ts,src/compiled-styles.css

sonar.javascript.lcov.reportPaths=coverage/frontend-v21/lcov.info
