spring.application.name=api-gateway
server.port=8087
eureka.client.service-url.defaultZone=${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.application.name}:${server.port}
spring.cloud.gateway.server.webflux.routes[0].id=imed-backend
spring.cloud.gateway.server.webflux.routes[0].uri=lb://imed-backend
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/**
spring.cloud.gateway.server.webflux.globalcors.add-to-simple-url-handler-mapping=true
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowedOrigins=http://localhost:4200
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowedMethods=GET,POST,PUT,DELETE,OPTIONS,PATCH
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowedHeaders=*
management.endpoints.web.exposure.include=health,info,gateway
