# Kubernetes Deployment for the Spring Boot Backend
apiVersion: apps/v1
kind: Deployment
metadata:
  name: imed-backend
  labels:
    app: imed-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: imed-backend
  template:
    metadata:
      labels:
        app: imed-backend
    spec:
      containers:
        - name: imed-backend
          # Docker Hub image — imedakrimi/imed-backend:latest
          image: imedakrimi/imed-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
