# Kubernetes Deployment for the Angular Frontend
apiVersion: apps/v1
kind: Deployment
metadata:
  name: imed-frontend
  labels:
    app: imed-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: imed-frontend
  template:
    metadata:
      labels:
        app: imed-frontend
    spec:
      containers:
        - name: imed-frontend
          # Docker Hub image — imedakrimi/imed-frontend:latest
          image: imedakrimi/imed-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
