spring.application.name=api-gateway
server.port=8080

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

spring.cloud.gateway.server.webflux.default-filters[0]=DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials Vary, RETAIN_FIRST

spring.cloud.gateway.server.webflux.routes[0].id=course-service-api
spring.cloud.gateway.server.webflux.routes[0].uri=lb://course-service
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/courses/**

spring.cloud.gateway.server.webflux.routes[1].id=course-service-uploads
spring.cloud.gateway.server.webflux.routes[1].uri=lb://course-service
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/uploads/**

spring.cloud.gateway.server.webflux.routes[2].id=quiz-service-api
spring.cloud.gateway.server.webflux.routes[2].uri=lb://quiz-service
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/api/quizzes/**

spring.cloud.gateway.server.webflux.routes[3].id=user-service-auth
spring.cloud.gateway.server.webflux.routes[3].uri=lb://user-service
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/api/auth/**

spring.cloud.gateway.server.webflux.routes[4].id=user-service-users
spring.cloud.gateway.server.webflux.routes[4].uri=lb://user-service
spring.cloud.gateway.server.webflux.routes[4].predicates[0]=Path=/api/users/**

management.endpoints.web.exposure.include=health,info,gateway

app.security.enabled=true
app.security.jwt.secret=${JWT_SECRET:VGhpcy1pcy1hLWRlbW8tbGVhcm5pdm8tand0LXNlY3JldC1rZXktdGhhdC1pcy1sb25nLWVub3VnaC0xMjM0NTY3ODkw}
