spring.application.name=api-gateway
server.port=8080

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

spring.cloud.gateway.server.webflux.default-filters[0]=DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials Vary, RETAIN_FIRST

spring.cloud.gateway.server.webflux.routes[0].id=course-service-api
spring.cloud.gateway.server.webflux.routes[0].uri=lb://course-service
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/courses/**

spring.cloud.gateway.server.webflux.routes[1].id=course-service-uploads
spring.cloud.gateway.server.webflux.routes[1].uri=lb://course-service
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/uploads/**

spring.cloud.gateway.server.webflux.routes[2].id=quiz-service-api
spring.cloud.gateway.server.webflux.routes[2].uri=lb://quiz-service
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/api/quizzes/**

management.endpoints.web.exposure.include=health,info,gateway
