apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-competition-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana-competition-service
  template:
    metadata:
      labels:
        app: grafana-competition-service
    spec:
      containers:
        - name: grafana
          image: grafana/grafana:latest
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-competition-service
spec:
  selector:
    app: grafana-competition-service
  ports:
    - port: 3000
      targetPort: 3000
  type: ClusterIP
